### ISSUE TITLE
Contributing guide does not explain how to run existing tests

### ISSUE THREAD

**Issue by BatmanAoD** [xuri/xgen#9]
**Description**

It is unclear how to run the existing `xgen` test suite, and it appears that doing so may require special permissions.

**Details:**

`CONTRIBUTING.md` recommends running the existing test suite, but does not give instructions for doing so. Running `go test ./...` in the root of the `xgen` repo results in the following error (repeated several times):

```
                Error:          Received unexpected error:
                                stat data/xsd: no such file or directory
```

Examining the GitHub Action workflow file, it appears that most of the tests live in a separate repository:

```yaml
    - name: Checkout test XSD
      uses: actions/checkout@v2
      with:
        repository: xuri/xsd
        token: ${{ secrets.GIT_TOKEN }}
        path: data
```

...however, it appears the github.com/xuri/xsd repo is private (I get a 404 from that URL).

**PS:**

I have elided most of the sections from the template because they don't seem relevant, since I am not reporting a bug in `xgen` behavior per se. I am happy to provide additional info if asked!

For context, I was hoping to investigate #7 because it is blocking my work.
